### PR TITLE
Closes #38 - Fix some SonarCloud issues

### LINKED ISSUE #38: Fix SonarCloud issues

### PR DESCRIPTION
**Pull request by CRoberto1926**
### Thanks for your PR! Please fill out the following list :)

---

- [x] I put the ticket or multiple tickets in review
- [x] Commit message format → Closes #&lt;Issue Number&gt; - Your commit message.
- [x] Sonarcloud link : https://sonarcloud.io/summary/new_code?id=CRoberto1926_KadaiAdapter&branch=chore%2Fsonarcloud-fixes
- [x] No documentation update needed
- [ ] Link to PR with documentation update: \<add the link here>
- [x] No Release Notes needed
- [ ] Release Notes :

```

```

### CODE REVIEW

File: kadai-adapter-camunda-listener/src/main/java/io/kadai/adapter/camunda/schemacreator/KadaiOutboxSchemaCreator.java [hunk 1]
```diff
@@ -47,12 +47,12 @@ public class KadaiOutboxSchemaCreator {
       SQL + "/postgres/kadai-outbox-schema-postgres.sql";
   private static final String DB_SCHEMA_ORACLE = SQL + "/oracle/kadai-outbox-schema-oracle.sql";
 
-  private DataSource dataSource;
-  private String schemaName;
-  private StringWriter outWriter = new StringWriter();
-  private PrintWriter logWriter = new PrintWriter(outWriter);
-  private StringWriter errorWriter = new StringWriter();
-  private PrintWriter errorLogWriter = new PrintWriter(errorWriter);
+  private final DataSource dataSource;
```
Comment (jamesrdi) [inline kadai-adapter-camunda-listener/src/main/java/io/kadai/adapter/camunda/schemacreator/KadaiOutboxSchemaCreator.java:50]: Did you add "final" because it is a code smell in sonarcloud?

File: kadai-adapter-camunda-outbox-rest/src/main/java/io/kadai/adapter/camunda/outbox/rest/service/CamundaTaskEventsService.java
Comment (jamesrdi) [inline kadai-adapter-camunda-outbox-rest/src/main/java/io/kadai/adapter/camunda/outbox/rest/service/CamundaTaskEventsService.java:1]: Did you only change the code formatting in this file?

File: kadai-adapter-camunda-spring-boot-test/src/test/java/io/kadai/adapter/integration/AbsIntegrationTest.java [hunk 2]
```diff
@@ -206,18 +203,16 @@ private void createWorkbasketAccessList(KadaiEngine engine, Workbasket wb) throw
     workbasketService.createWorkbasketAccessItem(workbasketAccessItem);
   }
 
-  private Classification createClassification(
-      KadaiEngine engine, String classificationKey, String domain) throws Exception {
+  private void createClassification(KadaiEngine engine, String classificationKey, String domain)
```
Comment (jamesrdi) [inline kadai-adapter-camunda-spring-boot-test/src/test/java/io/kadai/adapter/integration/AbsIntegrationTest.java:205]: Why did you change it to a void

File: kadai-adapter-camunda-spring-boot-test/src/test/java/io/kadai/impl/configuration/DbCleaner.java [hunk 3]
```diff
@@ -40,14 +40,14 @@ public class DbCleaner {
   private static final String KADAI_ADAPTER_DB_CLEAR_POSTGRES =
       "/sql/clear-kadai-adapter-db-postgres.sql";
   private static final String OUTBOX_DB_CLEAR_POSTGRES = "/sql/clear-outbox-db-postgres.sql";
-  private Map<ApplicationDatabaseType, String> typeScriptMap =
+  private final Map<ApplicationDatabaseType, String> typeScriptMap =
```
Comment (jamesrdi) [inline kadai-adapter-camunda-spring-boot-test/src/test/java/io/kadai/impl/configuration/DbCleaner.java:43]: Why did you add final?

File: kadai-adapter-camunda-spring-boot-test/src/test/java/io/kadai/impl/configuration/DbCleaner.java [hunk 4]
```diff
@@ -86,12 +86,12 @@ public void clearDb(DataSource dataSource, ApplicationDatabaseType applicationDa
...
 
     } catch (Exception e) {
-      LOGGER.error("caught Exception " + e);
+      LOGGER.error("caught Exception {}", e.getMessage(), e);
     }
     LOGGER.debug(outWriter.toString());
     String errorMsg = errorWriter.toString().trim();
 
-    if (!errorMsg.isEmpty() && errorMsg.indexOf("SQLCODE=-204, SQLSTATE=42704") == -1) {
+    if (!errorMsg.isEmpty() && !errorMsg.contains("SQLCODE=-204, SQLSTATE=42704")) {
```
Comment (jamesrdi) [inline kadai-adapter-camunda-spring-boot-test/src/test/java/io/kadai/impl/configuration/DbCleaner.java:94]: Why did you change it to use contains?

File: kadai-adapter-camunda-system-connector/src/main/java/io/kadai/adapter/systemconnector/camunda/api/impl/CamundaSystemConnectorImpl.java [hunk 5]
```diff
@@ -46,21 +46,21 @@ public class CamundaSystemConnectorImpl implements SystemConnector {
   static final String BODY_SET_ASSIGNEE = "{\"userId\":";
   static final String UNCLAIM_TASK = "/unclaim";
 
-  private CamundaSystemUrls.SystemUrlInfo camundaSystemUrl;
+  private final CamundaSystemUrls.SystemUrlInfo camundaSystemUrl;
```
Comment (jamesrdi) [inline kadai-adapter-camunda-system-connector/src/main/java/io/kadai/adapter/systemconnector/camunda/api/impl/CamundaSystemConnectorImpl.java:49]: Why did you change it to final

File: kadai-adapter-camunda-system-connector/src/main/java/io/kadai/adapter/systemconnector/camunda/api/impl/CamundaTaskRetriever.java [hunk 6]
```diff
@@ -108,7 +114,7 @@ private List<CamundaTaskEvent> getCamundaTaskEvents(
           restTemplate.exchange(
               requestUrl,
               HttpMethod.GET,
-              new HttpEntity<Object>(headers),
+              new HttpEntity<>(headers),
```
Comment (jamesrdi) [inline kadai-adapter-camunda-system-connector/src/main/java/io/kadai/adapter/systemconnector/camunda/api/impl/CamundaTaskRetriever.java:117]: Why did you change the generic?

File: kadai-adapter-camunda-system-connector/src/main/java/io/kadai/adapter/systemconnector/camunda/config/CamundaSystemConnectorConfiguration.java [hunk 7]
```diff
@@ -73,27 +74,34 @@ Integer getFromKadaiToAdapterBatchSize(
 
   @Bean
   @DependsOn(value = {"httpHeaderProvider"})
-  CamundaTaskRetriever camundaTaskRetriever() {
-    return new CamundaTaskRetriever();
+  CamundaTaskRetriever camundaTaskRetriever(
```
Comment (jamesrdi) [inline kadai-adapter-camunda-system-connector/src/main/java/io/kadai/adapter/systemconnector/camunda/config/CamundaSystemConnectorConfiguration.java:77]: Why did you add new parameters

File: kadai-adapter-camunda-system-connector/src/test/java/io/kadai/camunda/camundasystemconnector/configuration/CamundaConnectorTestConfiguration.java [hunk 8]
```diff
@@ -67,12 +67,16 @@ HttpHeaderProvider httpHeaderProvider() {
   }
 
   @Bean
-  CamundaTaskRetriever camundaTaskRetriever() {
-    return new CamundaTaskRetriever();
+  CamundaTaskRetriever camundaTaskRetriever(
```
Comment (jamesrdi) [inline kadai-adapter-camunda-system-connector/src/test/java/io/kadai/camunda/camundasystemconnector/configuration/CamundaConnectorTestConfiguration.java:70]: Why did you add new parameters?

File: kadai-adapter-kadai-connector/src/main/java/io/kadai/adapter/kadaiconnector/api/impl/KadaiSystemConnectorImpl.java [hunk 9]
```diff
@@ -40,29 +39,29 @@
...
   private static final String TASK_STATE_TERMINATED = "TERMINATED";
   private static final Logger LOGGER = LoggerFactory.getLogger(KadaiSystemConnectorImpl.class);
 
-  @Autowired private TaskService taskService;
-  @Autowired private KadaiEngine kadaiEngine;
+  private final TaskService taskService;
+  private final TaskInformationMapper taskInformationMapper;
 
-  @Autowired private TaskInformationMapper taskInformationMapper;
+  public KadaiSystemConnectorImpl(
```
Comment (jamesrdi) [inline kadai-adapter-kadai-connector/src/main/java/io/kadai/adapter/kadaiconnector/api/impl/KadaiSystemConnectorImpl.java:59]: Where is the constructor injection for kadaiEngine and kadaiDataSource?

File: kadai-adapter/src/main/java/io/kadai/adapter/configuration/AdapterConfiguration.java [hunk 10]
```diff
@@ -40,42 +39,34 @@
 @EnableTransactionManagement
 public class AdapterConfiguration {
 
-  @Value("${.jndi-name:no-jndi-configured}")
-  private String jndiName;
-
-  @Bean
-  @Scope(ConfigurableBeanFactory.SCOPE_SINGLETON)
```
Comment (jamesrdi) [inline kadai-adapter/src/main/java/io/kadai/adapter/configuration/AdapterConfiguration.java:47]: Why did you delete this Bean

File: kadai-adapter/src/main/java/io/kadai/adapter/configuration/AdapterConfiguration.java [hunk 11]
```diff
@@ -40,42 +39,34 @@
...
-  public AdapterManager manager() {
-    return new AdapterManager();
-  }
-
   @Bean
   @Scope(ConfigurableBeanFactory.SCOPE_SINGLETON)
-  public ReferencedTaskCompleter referencedTaskCompleter() {
-    return new ReferencedTaskCompleter();
+  public ReferencedTaskCompleter referencedTaskCompleter(final AdapterManager adapterManager) {
```
Comment (jamesrdi) [inline kadai-adapter/src/main/java/io/kadai/adapter/configuration/AdapterConfiguration.java]: Why did you add new parameters

File: kadai-adapter-camunda-listener/src/main/java/io/kadai/adapter/camunda/schemacreator/KadaiOutboxSchemaCreator.java (hunk 1 above)
Comment (CRoberto1926) [reply kadai-adapter-camunda-listener/src/main/java/io/kadai/adapter/camunda/schemacreator/KadaiOutboxSchemaCreator.java:50]: No, in general it is better to have finals, because it guarantees that the variable won't be reassigned. It could avoid some nasty bugs in complicated methods. I don't remember if SonarCloud or IntelliJ highlights it as an issue

File: kadai-adapter-camunda-outbox-rest/src/main/java/io/kadai/adapter/camunda/outbox/rest/service/CamundaTaskEventsService.java
Comment (CRoberto1926) [reply kadai-adapter-camunda-outbox-rest/src/main/java/io/kadai/adapter/camunda/outbox/rest/service/CamundaTaskEventsService.java:1]: Hmm it looks like that... Maybe I changed something at some point to try and fix some tests, but it was not necessary, and only the formatting changed.

File: kadai-adapter-camunda-spring-boot-test/src/test/java/io/kadai/adapter/integration/AbsIntegrationTest.java (hunk 2 above)
Comment (CRoberto1926) [reply kadai-adapter-camunda-spring-boot-test/src/test/java/io/kadai/adapter/integration/AbsIntegrationTest.java:205]: Because the return value was never used :)

File: kadai-adapter-camunda-spring-boot-test/src/test/java/io/kadai/impl/configuration/DbCleaner.java (hunk 3 above)
Comment (CRoberto1926) [reply kadai-adapter-camunda-spring-boot-test/src/test/java/io/kadai/impl/configuration/DbCleaner.java:43]: See the explanation above

File: kadai-adapter-camunda-spring-boot-test/src/test/java/io/kadai/impl/configuration/DbCleaner.java (hunk 4 above)
Comment (CRoberto1926) [reply kadai-adapter-camunda-spring-boot-test/src/test/java/io/kadai/impl/configuration/DbCleaner.java:94]: Because it does exactly the same thing, and it is much more readable than the previous version.

File: kadai-adapter-camunda-system-connector/src/main/java/io/kadai/adapter/systemconnector/camunda/api/impl/CamundaSystemConnectorImpl.java (hunk 5 above)
Comment (CRoberto1926) [reply kadai-adapter-camunda-system-connector/src/main/java/io/kadai/adapter/systemconnector/camunda/api/impl/CamundaSystemConnectorImpl.java:49]: See explanation above

File: kadai-adapter-camunda-system-connector/src/main/java/io/kadai/adapter/systemconnector/camunda/api/impl/CamundaTaskRetriever.java (hunk 6 above)
Comment (CRoberto1926) [reply kadai-adapter-camunda-system-connector/src/main/java/io/kadai/adapter/systemconnector/camunda/api/impl/CamundaTaskRetriever.java:117]: Because the compiler infers it automatically: https://docs.oracle.com/javase/7/docs/technotes/guides/language/type-inference-generic-instance-creation.html

File: kadai-adapter-camunda-system-connector/src/main/java/io/kadai/adapter/systemconnector/camunda/config/CamundaSystemConnectorConfiguration.java (hunk 7 above)
Comment (CRoberto1926) [reply kadai-adapter-camunda-system-connector/src/main/java/io/kadai/adapter/systemconnector/camunda/config/CamundaSystemConnectorConfiguration.java:77]: Because I switched from `@Autowired` to constructor injection

File: kadai-adapter-camunda-system-connector/src/test/java/io/kadai/camunda/camundasystemconnector/configuration/CamundaConnectorTestConfiguration.java (hunk 8 above)
Comment (CRoberto1926) [reply kadai-adapter-camunda-system-connector/src/test/java/io/kadai/camunda/camundasystemconnector/configuration/CamundaConnectorTestConfiguration.java:70]: See above

File: kadai-adapter-kadai-connector/src/main/java/io/kadai/adapter/kadaiconnector/api/impl/KadaiSystemConnectorImpl.java (hunk 9 above)
Comment (CRoberto1926) [reply kadai-adapter-kadai-connector/src/main/java/io/kadai/adapter/kadaiconnector/api/impl/KadaiSystemConnectorImpl.java:59]: What do you mean exactly?

File: kadai-adapter/src/main/java/io/kadai/adapter/configuration/AdapterConfiguration.java (hunk 10 above)
Comment (CRoberto1926) [reply kadai-adapter/src/main/java/io/kadai/adapter/configuration/AdapterConfiguration.java:47]: Because `AdapterManager` is already annotated as `@Component`, and Spring is creating and managing the Bean without having to create one in the configuration.

File: kadai-adapter/src/main/java/io/kadai/adapter/configuration/AdapterConfiguration.java (hunk 11 above)
Comment (CRoberto1926) [reply kadai-adapter/src/main/java/io/kadai/adapter/configuration/AdapterConfiguration.java]: For constructor injection instead of `@Autowired`

File: kadai-adapter-kadai-connector/src/main/java/io/kadai/adapter/kadaiconnector/api/impl/KadaiSystemConnectorImpl.java (hunk 9 above)
Comment (jamesrdi) [reply kadai-adapter-kadai-connector/src/main/java/io/kadai/adapter/kadaiconnector/api/impl/KadaiSystemConnectorImpl.java:59]: I meant, shouldn't you also put kadaiEngine and kadaiDataSource in the constructor, because you deleted the @Autowired of them

Comment (CRoberto1926) [reply kadai-adapter-kadai-connector/src/main/java/io/kadai/adapter/kadaiconnector/api/impl/KadaiSystemConnectorImpl.java:59]: I deleted them because they were not used :)

File: kadai-adapter-camunda-outbox-rest/src/main/java/io/kadai/adapter/camunda/outbox/rest/service/CamundaTaskEventsService.java
Comment (jamesrdi) [reply kadai-adapter-camunda-outbox-rest/src/main/java/io/kadai/adapter/camunda/outbox/rest/service/CamundaTaskEventsService.java:1]: Then maybe we can rewind the changes, since they dont fix the sonarcloud issues

**Review by jamesrdi — CHANGES_REQUESTED** [review]
Can you undo the changes in CamundaTaskEventsService.java since there is only formatting changes, and can you rebase the PR?

File: kadai-adapter-camunda-outbox-rest/src/main/java/io/kadai/adapter/camunda/outbox/rest/service/CamundaTaskEventsService.java
Comment (CRoberto1926) [reply kadai-adapter-camunda-outbox-rest/src/main/java/io/kadai/adapter/camunda/outbox/rest/service/CamundaTaskEventsService.java:1]: done

**Review by jamesrdi — APPROVED** [review]
