### PR TITLE
Closes #439 - Fix C7-, Outbox- and Scheduler Health-Check

### LINKED ISSUE #439: C7/Outbox Health-Check fails 401 due missing header and init captured null run causes NPE

### PR DESCRIPTION
**Pull request by bruderj15**
## Definition of Done

- [x] The corresponding ticket is in state `In Review`
- [x] The corresponding ticket is attached to this Pull-Request
- [x] The commit-message-format `Closes #ISSUE_ID - PROBLEM/SOLUTION`
    - is present as single-commit already or
    - will be squashed on merge
- [x] The changes pass the SonarQubeCloud-Quality-Gate
- [x] If the documentation needs an update, following there's a link to it:
- [x] If extra release-notes are required, they're listed indented below:

### CODE REVIEW

File: kadai-adapter-camunda7-parent/kadai-adapter-camunda-system-connector/src/main/java/io/kadai/adapter/monitoring/Camunda7OutboxHealthComposite.java [hunk 1]
```diff
@@ -17,13 +18,16 @@ public Camunda7OutboxHealthComposite(
...
       String camundaUrl,
       String outboxUrl,
-      Camunda7HealthConfigurationProperties properties) {
+      Camunda7HealthConfigurationProperties properties,
+      HttpHeaderProvider httpHeaderProvider) {
 
     if (properties.getCamunda().getEnabled()) {
-      healthContributors.put("camunda", new Camunda7HealthIndicator(restClient, camundaUrl));
+      healthContributors.put(
+          "camunda", new Camunda7HealthIndicator(restClient, httpHeaderProvider, camundaUrl));
```
Comment (gitgoodjhe) [inline kadai-adapter-camunda7-parent/kadai-adapter-camunda-system-connector/src/main/java/io/kadai/adapter/monitoring/Camunda7OutboxHealthComposite.java:26]: should we put these magic strings into constants/Config or something? ("camunda", "outbox")

**Review by gitgoodjhe — CHANGES_REQUESTED** [review]

File: kadai-adapter-camunda7-parent/kadai-adapter-camunda-system-connector/src/main/java/io/kadai/adapter/monitoring/Camunda7OutboxHealthComposite.java (hunk 1 above)
Comment (bruderj15) [reply kadai-adapter-camunda7-parent/kadai-adapter-camunda-system-connector/src/main/java/io/kadai/adapter/monitoring/Camunda7OutboxHealthComposite.java:26]: I personally prefer them inlined for JSON-fields.
Can't quite see the value of binding them to some const if barely used.
Even contrary: hurts readability.

**Review by gitgoodjhe — APPROVED** [review]
