### PR TITLE
Closes #221 - Fix cycle where C8-Tasks would be attempted to be cancelled multiple times

### LINKED ISSUE #221: C8: unwanted reaction when completing a task in kadai
- when a task is completed in kadai camunda is informed by the REST API 
- then camunda informs kadai again about the completion by the user-task-listener
- we need to make sure that kadai know that the task has already been completed to supress unnecessary operations

C7:
- in the method `setCompletionByKadaiAdapterAsLocalVariable` we set a local camunda variable when informing camunda about the completion 
- then in `taskWasCompletedByKadaiAdapter` we check for this variable and ignore the listener notification if the task comes originaly from kadai

### PR DESCRIPTION
**Pull request by bruderj15**
## Definition of Done

- [x] The corresponding ticket is in state `In Review`
- [x] The corresponding ticket is attached to this Pull-Request
- [x] The commit-message-format `Closes #ISSUE_ID - PROBLEM/SOLUTION`
    - is present as single-commit already or
    - will be squashed on merge
- [ ] The changes pass the SonarQubeCloud-Quality-Gate
- [x] If the documentation needs an update, following there's a link to it:
- [x] If extra release-notes are required, they're listed indented below:
  - While this technically is a breaking change due to the external task-id's pattern being changed (`c8sysid-<camunda8-system-id>-utk-<user-task-key>-eik-<element-instance-key>`), we won't treat it as one as the C8-Plugin was experimental until now

### CODE REVIEW

File: kadai-adapter-camunda8-parent/kadai-adapter-camunda-8-system-connector/src/main/java/io/kadai/adapter/systemconnector/camunda/api/impl/Camunda8TaskCompleter.java [hunk 1]
```diff
@@ -41,9 +42,12 @@ public SystemResponse completeCamunda8Task(ReferencedTask referencedTask) {
 
     if (completingEnabled) {
       try {
+        final String variables =
+            String.format(
+                "{%s, %s}", referencedTask.getVariables(), TASK_COMPLETED_BY_KADAI_KV_PAIR);
         camundaClient
             .newCompleteUserTaskCommand(getUserTaskKeyFromReferencedTask(referencedTask))
-            .variables("{" + referencedTask.getVariables() + "}")
+            .variables(variables)
```
Comment (leantios) [inline kadai-adapter-camunda8-parent/kadai-adapter-camunda-8-system-connector/src/main/java/io/kadai/adapter/systemconnector/camunda/api/impl/Camunda8TaskCompleter.java]: How about using [this endpt](https://docs.camunda.io/docs/apis-tools/orchestration-cluster-api-rest/specifications/create-element-instance-variables/): 
```
camundaClient.newSetVariablesCommand(elementInstanceKey)
            .variable(variables)
            .local(true)
            .send()
            .join();
```
The only downside is, that we need the elementInstanceKey here.

File: kadai-adapter-camunda8-parent/kadai-adapter-camunda-8-system-connector/src/test/java/io/kadai/adapter/systemconnector/camunda/api/impl/Camunda8TaskCompleterTest.java [hunk 2]
```diff
@@ -64,5 +64,46 @@ void should_CompleteCamundaTask_When_KadaiTaskIsCompleted() throws Exception {
...
+
+    final Task completedKadaiTask = kadaiEngine.getTaskService().getTask(kadaiTask.getId());
+    assertThat(completedKadaiTask.getState()).isEqualTo(TaskState.CANCELLED);
+    String externalId = kadaiTask.getExternalId();
+
+    long camundaTaskKey = Long.parseLong(externalId.substring(externalId.lastIndexOf("-") + 1));
+    camunda8TestUtil.waitUntil(
+        () -> "COMPLETED".equals(camunda8TestUtil.getCamundaTaskStatus(camundaTaskKey)));
+
+    CamundaAssert.assertThat(processInstance).isCompleted();
```
Comment (leantios) [inline kadai-adapter-camunda8-parent/kadai-adapter-camunda-8-system-connector/src/test/java/io/kadai/adapter/systemconnector/camunda/api/impl/Camunda8TaskCompleterTest.java:162]: Can we also check the monitoredRun here?

**Review by leantios — CHANGES_REQUESTED** [review]

File: kadai-adapter-camunda8-parent/kadai-adapter-camunda-8-system-connector/src/main/java/io/kadai/adapter/systemconnector/camunda/api/impl/Camunda8TaskCompleter.java (hunk 1 above)
Comment (bruderj15) [reply kadai-adapter-camunda8-parent/kadai-adapter-camunda-8-system-connector/src/main/java/io/kadai/adapter/systemconnector/camunda/api/impl/Camunda8TaskCompleter.java]: Why though? It already works with completion.

Edit: Ah the local part.

File: kadai-adapter-camunda8-parent/kadai-adapter-camunda-8-system-connector/src/test/java/io/kadai/adapter/systemconnector/camunda/api/impl/Camunda8TaskCompleterTest.java (hunk 2 above)
Comment (bruderj15) [reply kadai-adapter-camunda8-parent/kadai-adapter-camunda-8-system-connector/src/test/java/io/kadai/adapter/systemconnector/camunda/api/impl/Camunda8TaskCompleterTest.java:162]: Technically yes - with some tricks.
Semantically it doesn't make sense here though.
I don't want to add it.

**Comment by bruderj15** [comment]
Also note #371

**Comment by bruderj15** [comment]
I recommend going with this - proven to be working - approach for now.
In parallel extend Kadai with Force-Cancellation in the Java Api (https://github.com/kadai-io/kadai/issues/1641).
If that works as expected and we get it done and integrated in time, **prefer the force-cancellation**  for release.

File: kadai-adapter-camunda8-parent/kadai-adapter-camunda-8-system-connector/src/main/java/io/kadai/adapter/systemconnector/camunda/tasklistener/UserTaskCompletion.java [hunk 3]
```diff
@@ -34,11 +36,20 @@ public UserTaskCompletion(
   @JobWorker(type = "kadai-receive-task-completed-event")
   public void receiveTaskCompletedEvent(final ActivatedJob job)
       throws TaskTerminationFailedException {
+    System.out.println("Foo:" + job.getVariables());
```
Comment (leantios) [inline kadai-adapter-camunda8-parent/kadai-adapter-camunda-8-system-connector/src/main/java/io/kadai/adapter/systemconnector/camunda/tasklistener/UserTaskCompletion.java]: Whoopsie

File: kadai-adapter-camunda8-parent/kadai-adapter-camunda-8-system-connector/src/main/java/io/kadai/adapter/systemconnector/camunda/tasklistener/util/ReferencedTaskCreator.java [hunk 4]
```diff
@@ -76,6 +76,42 @@ public ReferencedTask createReferencedTaskFromJob(ActivatedJob job) {
...
 
+  public static String resolveTaskId(ActivatedJob activatedJob, Camunda8System camunda8System) {
+    return String.format(
+        "c8sysid-%d-utk-%d-eik-%d",
+        camunda8System.getIdentifier(),
+        activatedJob.getUserTask().getUserTaskKey(),
+        activatedJob.getElementInstanceKey());
+  }
+
+  public static Long extractUserTaskKeyFromTaskId(String taskId) {
```
Comment (leantios) [inline kadai-adapter-camunda8-parent/kadai-adapter-camunda-8-system-connector/src/main/java/io/kadai/adapter/systemconnector/camunda/tasklistener/util/ReferencedTaskCreator.java:87]: Feels wrong to have this here due to Single Responsibility Principle: this is a class for creating a referenced task, not a class with all kinds of utilities

File: kadai-adapter-camunda8-parent/kadai-adapter-camunda-8-system-connector/src/main/java/io/kadai/adapter/systemconnector/camunda/tasklistener/UserTaskCancellation.java [hunk 5]
```diff
@@ -1,5 +1,7 @@
 package io.kadai.adapter.systemconnector.camunda.tasklistener;
 
+import static io.kadai.adapter.systemconnector.camunda.api.impl.Camunda8TaskCompleter.TASK_COMPLETED_BY_KADAI_KV_PAIR;
```
Comment (leantios) [inline kadai-adapter-camunda8-parent/kadai-adapter-camunda-8-system-connector/src/main/java/io/kadai/adapter/systemconnector/camunda/tasklistener/UserTaskCancellation.java]: I am not completely happy about this solution. Maybe define a class with Constants and add it there?

File: kadai-adapter-camunda8-parent/kadai-adapter-camunda-8-system-connector/src/test/java/io/kadai/adapter/systemconnector/camunda/api/impl/Camunda8TaskCompleterTest.java [hunk 6]
```diff
@@ -61,8 +62,49 @@ void should_CompleteCamundaTask_When_KadaiTaskIsCompleted() throws Exception {
...
+
+    final Task completedKadaiTask = kadaiEngine.getTaskService().getTask(kadaiTask.getId());
+    assertThat(completedKadaiTask.getState()).isEqualTo(TaskState.CANCELLED);
+    String externalId = kadaiTask.getExternalId();
+
+    long camundaTaskKey = ReferencedTaskCreator.extractUserTaskKeyFromTaskId(externalId);
+    camunda8TestUtil.waitUntil(
+        () -> "COMPLETED".equals(camunda8TestUtil.getCamundaTaskStatus(camundaTaskKey)));
+
+    CamundaAssert.assertThat(processInstance).isCompleted();
```
Comment (leantios) [inline kadai-adapter-camunda8-parent/kadai-adapter-camunda-8-system-connector/src/test/java/io/kadai/adapter/systemconnector/camunda/api/impl/Camunda8TaskCompleterTest.java:162]: We should test here whether the variable was set

**Review by leantios — CHANGES_REQUESTED** [review]

File: kadai-adapter-camunda8-parent/kadai-adapter-camunda-8-system-connector/src/main/java/io/kadai/adapter/systemconnector/camunda/tasklistener/util/ReferencedTaskCreator.java (hunk 4 above)
Comment (bruderj15) [reply kadai-adapter-camunda8-parent/kadai-adapter-camunda-8-system-connector/src/main/java/io/kadai/adapter/systemconnector/camunda/tasklistener/util/ReferencedTaskCreator.java:87]: Tbf, this isn't perfect, yes. In fact `ReferencedTask` itself should encapsulate this information by exposing a getter.
This however, is caused by #211.

What I did here is then better than scattering the code-base which would be the result of your proposal.
In here, `ReferencedTaskCreator` is the owner of the logic for creation of discussed field.
Hence why it is this class that must expose the information and therefore hide how to decompose the string.

File: kadai-adapter-camunda8-parent/kadai-adapter-camunda-8-system-connector/src/main/java/io/kadai/adapter/systemconnector/camunda/tasklistener/UserTaskCancellation.java (hunk 5 above)
Comment (bruderj15) [reply kadai-adapter-camunda8-parent/kadai-adapter-camunda-8-system-connector/src/main/java/io/kadai/adapter/systemconnector/camunda/tasklistener/UserTaskCancellation.java]: Similar argument as above. It is `Camunda8TaskCompleter` owning the behavior. Therefore the constant should be defined there.

Comment (bruderj15) [reply kadai-adapter-camunda8-parent/kadai-adapter-camunda-8-system-connector/src/main/java/io/kadai/adapter/systemconnector/camunda/tasklistener/UserTaskCancellation.java]: You were right that we would decouple completer and task-listener by introducing a central (bus-like) place.
Overkill here though.

**Comment by bruderj15** [comment]
I kept the composite key although we don't need the element-instance-key anymore.
Imo good to be in there.

**Review by leantios — DISMISSED** [review]
Looks good to me :)
